LemurVim.plugins["which-key"] = {
  "folke/which-key.nvim",
  config = function()
    local wk = require("which-key")

    wk.setup({
      -- 登记常见前缀和 Neovim 默认按键的中文说明，避免 which-key 面板里出现大量英文描述。
      spec = {
        { "<leader>f", group = "文件 / 查找" },
        { "<leader>g", group = "Git" },
        { "<leader>gh", group = "Git 变更块" },
        { "<leader>s", group = "搜索 / 列表" },
        { "<leader>u", group = "工具 / UI" },
        { "<leader>m", group = "Markdown" },

        { "g", group = "跳转 / 文本操作" },
        { "g#", desc = "反向搜索光标下词（非整词）" },
        { "g$", desc = "到屏幕行行尾" },
        { "g&", desc = "对所有行重复上次替换" },
        { "g'", desc = "跳转到标记（不修改跳转列表）" },
        { "g`", desc = "跳转到标记精确位置（不修改跳转列表）" },
        { "g*", desc = "搜索光标下词（非整词）" },
        { "g+", desc = "更新的文本状态" },
        { "g,", desc = "更新列表：上一个位置" },
        { "g-", desc = "更早的文本状态" },
        { "g0", desc = "到屏幕行行首" },
        { "g8", desc = "显示光标字符 UTF-8 字节" },
        { "g<", desc = "查看上次命令输出" },
        { "g?", desc = "ROT13 编码操作符" },
        { "g??", desc = "当前行 ROT13 编码" },
        { "g?g?", desc = "当前行 ROT13 编码" },
        { "gD", desc = "跳转到全局声明" },
        { "gE", desc = "向后到 WORD 词尾" },
        { "gH", desc = "选择行模式" },
        { "gI", desc = "跳转到实现" },
        { "gJ", desc = "连接行（不插入空格）" },
        { "gN", desc = "选择上一个搜索匹配" },
        { "gQ", desc = "进入 Ex 模式" },
        { "gR", desc = "虚拟替换模式" },
        { "gT", desc = "上一个标签页" },
        { "gU", desc = "转大写操作符" },
        { "ga", desc = "显示光标字符编码" },
        { "gd", desc = "跳转到定义" },
        { "ge", desc = "向后到词尾" },
        { "gg", desc = "到文件开头" },
        { "gh", desc = "选择模式" },
        { "gi", desc = "回到上次插入位置并插入" },
        { "gj", desc = "向下移动一个屏幕行" },
        { "gk", desc = "向上移动一个屏幕行" },
        { "gm", desc = "到屏幕行中间" },
        { "gn", desc = "选择下一个搜索匹配" },
        { "go", desc = "跳转到字节位置" },
        { "gp", desc = "粘贴并把光标放到粘贴内容之后" },
        { "gq", desc = "格式化操作符" },
        { "gr", desc = "引用" },
        { "gs", desc = "睡眠" },
        { "gt", desc = "下一个标签页" },
        { "gu", desc = "转小写操作符" },
        { "gv", desc = "重新选择上次可视区域" },
        { "gw", desc = "格式化文本（保持光标）" },
        { "gx", desc = "打开光标下链接/文件" },
        { "gy", desc = "跳转到类型定义" },
        { "g~", desc = "大小写切换操作符" },
      },
    })
  end,
}
