LemurVim.plugins["which-key"] = {
  "folke/which-key.nvim",
  config = function()
    local wk = require("which-key")

    wk.setup({
      -- 登记常见前缀和 Neovim 默认按键的中文说明，避免 which-key 面板里出现大量英文描述。
      spec = {
        -- <leader> 分组
        { "<leader>b", group = "缓冲区" },
        { "<leader>c", group = "代码 / LSP" },
        { "<leader>e", group = "文件树 / 资源管理器" },
        { "<leader>f", group = "文件 / 查找" },
        { "<leader>g", group = "Git" },
        { "<leader>gh", group = "Git 变更块" },
        { "<leader>l", group = "Live Server" },
        { "<leader>m", group = "Markdown" },
        { "<leader>n", group = "通知 / 清除" },
        { "<leader>s", group = "搜索 / 列表" },
        { "<leader>u", group = "工具 / UI" },

        -- 普通模式下的非 leader 前缀分组
        { "[", group = "上一个（诊断 / hunk / 位置）" },
        { "]", group = "下一个（诊断 / hunk / 位置）" },
        { '"', group = "寄存器" },
        { "'", group = "标记（行）" },
        { "`", group = "标记（精确位置）" },
        { "@", group = "宏 / 寄存器回放" },
        { "<C-w>", group = "窗口" },

        { "g", group = "跳转 / 文本操作" },
        { "g#", desc = "反向搜索光标下词（非整词）" },
        { "g$", desc = "到屏幕行行尾" },
        { "g&", desc = "对所有行重复上次替换" },
        { "g'", desc = "跳转到标记（不修改跳转列表）" },
        { "g`", desc = "跳转到标记精确位置（不修改跳转列表）" },
        { "g*", desc = "搜索光标下词（非整词）" },
        { "g+", desc = "更新的文本状态" },
        { "g,", desc = "更新列表：上一个位置" },
        { "g-", desc = "更早的文本状态" },
        { "g0", desc = "到屏幕行行首" },
        { "g8", desc = "显示光标字符 UTF-8 字节" },
        { "g<", desc = "查看上次命令输出" },
        { "g?", desc = "ROT13 编码操作符" },
        { "g??", desc = "当前行 ROT13 编码" },
        { "g?g?", desc = "当前行 ROT13 编码" },
        { "gD", desc = "跳转到全局声明" },
        { "gE", desc = "向后到 WORD 词尾" },
        { "gH", desc = "选择行模式" },
        { "gI", desc = "跳转到实现" },
        { "gJ", desc = "连接行（不插入空格）" },
        { "gN", desc = "选择上一个搜索匹配" },
        { "gQ", desc = "进入 Ex 模式" },
        { "gR", desc = "虚拟替换模式" },
        { "gT", desc = "上一个标签页" },
        { "gU", desc = "转大写操作符" },
        { "ga", desc = "显示光标字符编码" },
        { "gd", desc = "跳转到定义" },
        { "ge", desc = "向后到词尾" },
        { "gg", desc = "到文件开头" },
        { "gh", desc = "选择模式" },
        { "gi", desc = "回到上次插入位置并插入" },
        { "gj", desc = "向下移动一个屏幕行" },
        { "gk", desc = "向上移动一个屏幕行" },
        { "gm", desc = "到屏幕行中间" },
        { "gn", desc = "选择下一个搜索匹配" },
        { "go", desc = "跳转到字节位置" },
        { "gp", desc = "粘贴并把光标放到粘贴内容之后" },
        { "gq", desc = "格式化操作符" },
        { "gr", desc = "引用" },
        { "gs", desc = "睡眠" },
        { "gt", desc = "下一个标签页" },
        { "gu", desc = "转小写操作符" },
        { "gv", desc = "重新选择上次可视区域" },
        { "gw", desc = "格式化文本（保持光标）" },
        { "gx", desc = "打开光标下链接/文件" },
        { "gy", desc = "跳转到类型定义" },
        { "g~", desc = "大小写切换操作符" },

        -- z 开头：光标定位、屏幕滚动、拼写检查、折叠
        { "z", group = "光标 / 滚动 / 折叠 / 拼写" },
        { "z<CR>", desc = "光标行置顶并定位到行首非空白" },
        { "z+", desc = "跳到下一个窗口首行的第一个非空白字符" },
        { "z-", desc = "光标行置底并定位到行首非空白" },
        { "z.", desc = "光标行居中并定位到行首非空白" },
        { "z=", desc = "拼写建议" },
        { "zA", desc = "切换折叠（递归，含嵌套）" },
        { "zC", desc = "递归折叠" },
        { "zD", desc = "递归删除折叠" },
        { "zE", desc = "删除窗口内所有折叠" },
        { "zF", desc = "在指定行范围创建折叠" },
        { "zG", desc = "把单词标记为正确拼写" },
        { "zH", desc = "屏幕向左水平滚动半个宽度" },
        { "zL", desc = "屏幕向右水平滚动半个宽度" },
        { "zM", desc = "关闭所有折叠（设置 foldlevel=0）" },
        { "zN", desc = "重新启用折叠" },
        { "zO", desc = "递归展开折叠" },
        { "zP", desc = "在预览窗口里查看跳转位置" },
        { "zR", desc = "打开所有折叠（设置 foldlevel 为最高）" },
        { "zW", desc = "把单词标记为错误拼写" },
        { "zX", desc = "重新应用 foldlevel 重置折叠" },
        { "z^", desc = "跳到上一个窗口末行的第一个非空白字符" },
        { "za", desc = "切换当前折叠" },
        { "zb", desc = "把当前行滚动到屏幕底部" },
        { "zc", desc = "关闭当前折叠" },
        { "zd", desc = "删除当前折叠" },
        { "ze", desc = "水平滚动使光标位于屏幕右侧" },
        { "zf", desc = "对文本对象/选中区域创建折叠" },
        { "zg", desc = "把单词加入拼写白名单" },
        { "zh", desc = "屏幕向右滚动一个字符" },
        { "zi", desc = "切换折叠启用状态" },
        { "zj", desc = "跳到下一个折叠" },
        { "zk", desc = "跳到上一个折叠" },
        { "zl", desc = "屏幕向左滚动一个字符" },
        { "zm", desc = "折叠一级（foldlevel 减 1）" },
        { "zn", desc = "禁用折叠（不重新计算）" },
        { "zo", desc = "打开当前折叠" },
        { "zr", desc = "展开一级（foldlevel 加 1）" },
        { "zs", desc = "水平滚动使光标位于屏幕左侧" },
        { "zt", desc = "把当前行滚动到屏幕顶部" },
        { "zu", desc = "拼写建议子组" },
        { "zug", desc = "撤销把单词加入拼写白名单" },
        { "zuw", desc = "把光标单词标记为错误拼写（等同于 zw）" },
        { "zuW", desc = "把光标 WORD 标记为错误拼写（等同于 zW）" },
        { "zv", desc = "展开足够折叠以显示光标所在行" },
        { "zw", desc = "把光标下单词标记为错误拼写" },
        { "zx", desc = "重新应用 foldlevel 并执行 zv" },
        { "zy", desc = "复制折叠状态（配合 zX 使用）" },
        { "zz", desc = "把当前行滚动到屏幕中间" },
        { "z<Right>", desc = "屏幕向右滚动一个字符（同 zh）" },
        { "z<Left>", desc = "屏幕向左滚动一个字符（同 zl）" },
      },
    })
  end,
}
